M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu23.04.1} date Mon Nov  6 23:53:30 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-11-06T23:53:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X-9660Y83527
X-9660Y2248
T2
X-9300Y67055
X-9300Y18845
T0
M30
