M48
; DRILL file {KiCad 8.0.8+1} date 2025-05-12T22:43:11+0000
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-05-12T22:43:11+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X-9660Y83527
X-9660Y2248
T2
X-9300Y67055
X-9300Y18845
M30
